mixin rb helper with doc helper

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -2,9 +2,11 @@
 
 #/ NAME
 #/     build -- upload the latest (timestamp) rubygem to rubygems.org
+#/     build -- builds static site using jekyll
 #/
 #/ SYNOPSIS
-#/     build -n gem_name
+#/     build gem -n gem_name
+#/     build site
 
 # figure out the project root under which bin, lib live
 shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
@@ -14,17 +16,52 @@ source "$shome/bin/_prime" "$@"
 
 # entry point
 function main {
-  pth_gemspec="$shome/$FLAGS_name.gemspec"
+  if [[ "$#" < 1 ]]; then
+    logger_fatal "missing component(s)"
+    exit 1
+  fi
+
+  local nm_component="$1"; shift
+
+  case "$nm_component" in 
+    gem)
+      build_gem "$@"
+    site)
+      build_site "$@"
+      ;;
+    *)
+      logger_fatal "don't know how to build ${nm_component}"
+      exit 1
+      ;;
+  esac
+}
+
+# build a gem
+function build_gem {
+  local pth_gemspec="$shome/$FLAGS_name.gemspec"
   if [[ ! -e "$pth_gemspec" ]]; then
     logger_fatal "could not find gemspec $pth_gemspec"
     exit 1
   fi
 
+  cd "$shome"
   gem build "$pth_gemspec"
 }
 
-# parse the command-line
+# build the site with jekyll
+function build_site {
+  export BUNDLE_GEMFILE="$shome/.doc/Gemfile"
+
+  cd $shome/site
+  bundle check 2>&1 >/dev/null || { bundle install --quiet --local --path vendor/bundle || bundle check > /dev/null; }
+  bundle exec jekyll
+}
+
+# define command line options:
+#   var name, default, description, short option
 DEFINE_string 'name' "$(basename "$shome")" 'name of gem' 'n'
+
+# parse the command-line
 parse_command_line "$@" || exit $?
 eval set -- "${FLAGS_ARGV}"
 
